name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci_cd_exercise_fe:latest
    - name: Check SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -l ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa | head -n 2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_AWS_PRIVATE_KEY }}
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_AWS_PRIVATE_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        HOST: ${{ secrets.AWS_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
        ssh "$USERNAME"@"$HOST" << 'EOF'
          source .bashrc
          cd ci-cd-excise
          git pull origin develop
          docker-compose down
          docker-compose pull $DOCKER_USERNAME/ci_cd_exercise_fe:latest
          docker-compose up -d
        EOF
